Jw/sign up
KarFarm/pomelo-web pull request #3
Opened 2021-11-24 04:21 UTC by jeongwon000

attached screenshot on another PR

didn't prevent users submitting the form when they don't agree to terms yet.

2021-11-25 04:48 UTC, elliott44k requested changes

2021-11-25 04:48 UTC, elliott44k commented on client/src/components/Article.js
> +import * as React from 'react';
Can we add a header comment describing what these files are doing?

2021-11-25 04:48 UTC, elliott44k commented on client/src/components/Description.js
> +import * as React from 'react';
Header here as well

2021-11-25 04:48 UTC, elliott44k commented on client/src/components/Article.js
> +import * as React from 'react';
Like this https://react-styleguidist.js.org/docs/documenting/ but with the header at the top instead of below the import statements

2021-11-25 04:48 UTC, elliott44k commented on client/src/components/Footer.js
> +import * as React from 'react';
Here header

2021-11-25 04:48 UTC, elliott44k commented on client/src/components/Header.js
> +import * as React from 'react';
Header

2021-11-25 04:48 UTC, elliott44k commented on client/src/components/ScreenSwiper.js
> +import { makeStyles } from "@mui/styles";
Header

2021-11-25 04:48 UTC, elliott44k commented on client/src/components/TextInput.js
> +import * as React from 'react';
Header

2021-11-25 04:48 UTC, elliott44k commented on client/src/styles/createTheme.js
>  import { createTheme } from '@mui/material/styles';
Here

2021-11-25 04:48 UTC, elliott44k commented on client/src/views/AppInfo.js
>  import * as React from 'react';
Here

2021-11-25 07:07 UTC, jeongwon000 commented
@elliott44k wrote missing headers! some components could be altered as now we get the design files.

2021-11-30 03:54 UTC, elliott44k approved these changes

2021-11-30 03:54 UTC, merged